name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Display cargo version
        run: cargo --version

      - name: Display cargo clippy version
        run: cargo clippy --version

      - name: Run clippy
        run: cargo clippy -- -D warnings

      - name: Run tests
        run: cargo test --locked

  code-style:
    name: Verify code style
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Verify code format
        run: cargo fmt -- --check
